### ISSUE TITLE
No valid associations found for deployment

### ISSUE THREAD

**Issue by ekulabuhov** [CircleCI-Public/jira-connect-orb#71] opened 2021-09-17 15:24 UTC
### Orb version

1.3.1

### What happened
Hi! We're having issues with reporting production deployments only. It works as expected for development deployments.

I found one case where it worked:
* https://app.circleci.com/pipelines/github/Kamion/kamion_server/3019/workflows/769a8261-a53d-4e42-9c13-3122705c0413/jobs/8685

And in the second case it didn't:
* https://app.circleci.com/pipelines/github/Kamion/kamion_server/3199/workflows/11fad98d-56c7-4c64-9e13-aec5e4d54212/jobs/9077

Is there any context behind this error: "No valid associations found for deployment"?

Also, I see that you're using some internal CircleCI API to report to JIRA. Is there a documentation for this endpoint?

### Expected behavior

Ideally, it should work.

**Comment by col** [comment] 2021-11-08 08:40
I'm having the same issue

**Comment by evanbreitsch** [comment] 2021-11-11 00:59
Same issue here

**Comment by KyleTryon** [comment] 2021-12-20 19:27
Dupe of #63

**Closed by KyleTryon** 2021-12-20 19:27 UTC
