### ISSUE TITLE
Add parameters to support reporting test status

### ISSUE THREAD

**Issue by jazwiecki** [CircleCI-Public/jira-connect-orb#75] opened 2021-11-20 21:57 UTC
### Orb version

1.3.1

### What happened

Jira's [build data API](https://developer.atlassian.com/cloud/jira/software/rest/api-group-builds/#api-builds-0-1-bulk-post) has optional test results parameters:

```
      "testInfo": {
        "totalNumber": 150,
        "numberPassed": 145,
        "numberFailed": 5,
        "numberSkipped": 0
      },
```

### Expected behavior

Orb supports passing `test_info_total_number`, `test_info_number_passed`, `test_info_number_failed`, and `test_info_number_skipped` integers into `build` notification `job_type`s.

**Comment by KyleTryon** [comment] 2021-12-20 18:37
Dupe of #27

**Closed by KyleTryon** 2021-12-20 18:37 UTC
